# Generated by Django 6.0.1 on 2026-01-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
    ]
