# Generated by Django 6.0.1 on 2026-01-31 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, unique=True)),
                ('lastname', models.CharField(max_length=150)),
                ('school', models.CharField(choices=[('NSCS', 'National School of Cybersecurity'), ('ENSIA', 'National School of Artificial Intelligence'), ('NHSM', 'National Higher School of Mathematics'), ('NHSAST', 'National Higher School of Autonomous Systems Technology'), ('NHSNNT', 'National Higher School of Nano And Nanotechnology'), ('ESI', 'National School of Computer Science'), ('ESI-SBA', 'National School of Computer Science Sidi Bel Abbes'), ('ESTIN', 'Higher School in Computer Science and Digital Technologies'), ('NIT', 'Numidia Institute of Technology'), ('Other', 'Other')], max_length=255)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year ')])),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('discord_id', models.CharField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname1', models.CharField(max_length=150, unique=True)),
                ('lastname1', models.CharField(max_length=150)),
                ('school1', models.CharField(choices=[('NSCS', 'National School of Cybersecurity'), ('ENSIA', 'National School of Artificial Intelligence'), ('NHSM', 'National Higher School of Mathematics'), ('NHSAST', 'National Higher School of Autonomous Systems Technology'), ('NHSNNT', 'National Higher School of Nano And Nanotechnology'), ('ESI', 'National School of Computer Science'), ('ESI-SBA', 'National School of Computer Science Sidi Bel Abbes'), ('ESTIN', 'Higher School in Computer Science and Digital Technologies'), ('NIT', 'Numidia Institute of Technology'), ('Other', 'Other')], max_length=255)),
                ('year1', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year ')])),
                ('student_id1', models.CharField(max_length=50, unique=True)),
                ('skills1', models.TextField(choices=[('Cryptography', 'Cryptography'), ('Web Security', 'Web Security'), ('PWN & Binary Exploitation', 'PWN & Binary Exploitation'), ('Reverse Engineering', 'Reverse Engineering'), ('Forensics', 'Forensics'), ('OSINT', 'OSINT'), ('Web Development', 'Web Development'), ('Programming', 'Programming'), ('problem Solving', 'Problem Solving'), ('Other', 'Other')], max_length=50)),
                ('profile_link1', models.URLField(blank=True, help_text='Link to your profile (GitHub, TryHackMe, CTFTime, etc.)', null=True)),
                ('email1', models.EmailField(max_length=254, unique=True)),
                ('discord_id1', models.CharField(max_length=100, unique=True)),
                ('firstname2', models.CharField(max_length=150, unique=True)),
                ('lastname2', models.CharField(max_length=150)),
                ('school2', models.CharField(choices=[('NSCS', 'National School of Cybersecurity'), ('ENSIA', 'National School of Artificial Intelligence'), ('NHSM', 'National Higher School of Mathematics'), ('NHSAST', 'National Higher School of Autonomous Systems Technology'), ('NHSNNT', 'National Higher School of Nano And Nanotechnology'), ('ESI', 'National School of Computer Science'), ('ESI-SBA', 'National School of Computer Science Sidi Bel Abbes'), ('ESTIN', 'Higher School in Computer Science and Digital Technologies'), ('NIT', 'Numidia Institute of Technology'), ('Other', 'Other')], max_length=255)),
                ('year2', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year ')])),
                ('student_id2', models.CharField(max_length=50, unique=True)),
                ('skills2', models.TextField(choices=[('Cryptography', 'Cryptography'), ('Web Security', 'Web Security'), ('PWN & Binary Exploitation', 'PWN & Binary Exploitation'), ('Reverse Engineering', 'Reverse Engineering'), ('Forensics', 'Forensics'), ('OSINT', 'OSINT'), ('Web Development', 'Web Development'), ('Programming', 'Programming'), ('problem Solving', 'Problem Solving'), ('Other', 'Other')], max_length=50)),
                ('profile_link2', models.URLField(blank=True, help_text='Link to your profile (GitHub, TryHackMe, CTFTime, etc.)', null=True)),
                ('email2', models.EmailField(max_length=254, unique=True)),
                ('discord_id2', models.CharField(max_length=100, unique=True)),
                ('firstname3', models.CharField(max_length=150, unique=True)),
                ('lastname3', models.CharField(max_length=150)),
                ('school3', models.CharField(choices=[('NSCS', 'National School of Cybersecurity'), ('ENSIA', 'National School of Artificial Intelligence'), ('NHSM', 'National Higher School of Mathematics'), ('NHSAST', 'National Higher School of Autonomous Systems Technology'), ('NHSNNT', 'National Higher School of Nano And Nanotechnology'), ('ESI', 'National School of Computer Science'), ('ESI-SBA', 'National School of Computer Science Sidi Bel Abbes'), ('ESTIN', 'Higher School in Computer Science and Digital Technologies'), ('NIT', 'Numidia Institute of Technology'), ('Other', 'Other')], max_length=255)),
                ('year3', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year ')])),
                ('student_id3', models.CharField(max_length=50, unique=True)),
                ('skills3', models.TextField(choices=[('Cryptography', 'Cryptography'), ('Web Security', 'Web Security'), ('PWN & Binary Exploitation', 'PWN & Binary Exploitation'), ('Reverse Engineering', 'Reverse Engineering'), ('Forensics', 'Forensics'), ('OSINT', 'OSINT'), ('Web Development', 'Web Development'), ('Programming', 'Programming'), ('problem Solving', 'Problem Solving'), ('Other', 'Other')], max_length=50)),
                ('profile_link3', models.URLField(blank=True, help_text='Link to your profile (GitHub, TryHackMe, CTFTime, etc.)', null=True)),
                ('email3', models.EmailField(max_length=254, unique=True)),
                ('discord_id3', models.CharField(max_length=100, unique=True)),
                ('firstname4', models.CharField(max_length=150, unique=True)),
                ('lastname4', models.CharField(max_length=150)),
                ('school4', models.CharField(choices=[('NSCS', 'National School of Cybersecurity'), ('ENSIA', 'National School of Artificial Intelligence'), ('NHSM', 'National Higher School of Mathematics'), ('NHSAST', 'National Higher School of Autonomous Systems Technology'), ('NHSNNT', 'National Higher School of Nano And Nanotechnology'), ('ESI', 'National School of Computer Science'), ('ESI-SBA', 'National School of Computer Science Sidi Bel Abbes'), ('ESTIN', 'Higher School in Computer Science and Digital Technologies'), ('NIT', 'Numidia Institute of Technology'), ('Other', 'Other')], max_length=255)),
                ('year4', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year ')])),
                ('student_id4', models.CharField(max_length=50, unique=True)),
                ('skills4', models.TextField(choices=[('Cryptography', 'Cryptography'), ('Web Security', 'Web Security'), ('PWN & Binary Exploitation', 'PWN & Binary Exploitation'), ('Reverse Engineering', 'Reverse Engineering'), ('Forensics', 'Forensics'), ('OSINT', 'OSINT'), ('Web Development', 'Web Development'), ('Programming', 'Programming'), ('problem Solving', 'Problem Solving'), ('Other', 'Other')], max_length=50)),
                ('profile_link4', models.URLField(blank=True, help_text='Link to your profile (GitHub, TryHackMe, CTFTime, etc.)', null=True)),
                ('email4', models.EmailField(max_length=254, unique=True)),
                ('discord_id4', models.CharField(max_length=100, unique=True)),
                ('firstname5', models.CharField(max_length=150, unique=True)),
                ('lastname5', models.CharField(max_length=150)),
                ('school5', models.CharField(choices=[('NSCS', 'National School of Cybersecurity'), ('ENSIA', 'National School of Artificial Intelligence'), ('NHSM', 'National Higher School of Mathematics'), ('NHSAST', 'National Higher School of Autonomous Systems Technology'), ('NHSNNT', 'National Higher School of Nano And Nanotechnology'), ('ESI', 'National School of Computer Science'), ('ESI-SBA', 'National School of Computer Science Sidi Bel Abbes'), ('ESTIN', 'Higher School in Computer Science and Digital Technologies'), ('NIT', 'Numidia Institute of Technology'), ('Other', 'Other')], max_length=255)),
                ('year5', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year ')])),
                ('student_id5', models.CharField(max_length=50, unique=True)),
                ('skills5', models.TextField(choices=[('Cryptography', 'Cryptography'), ('Web Security', 'Web Security'), ('PWN & Binary Exploitation', 'PWN & Binary Exploitation'), ('Reverse Engineering', 'Reverse Engineering'), ('Forensics', 'Forensics'), ('OSINT', 'OSINT'), ('Web Development', 'Web Development'), ('Programming', 'Programming'), ('problem Solving', 'Problem Solving'), ('Other', 'Other')], max_length=50)),
                ('profile_link5', models.URLField(blank=True, help_text='Link to your profile (GitHub, TryHackMe, CTFTime, etc.)', null=True)),
                ('email5', models.EmailField(max_length=254, unique=True)),
                ('discord_id5', models.CharField(max_length=100, unique=True)),
                ('team_name', models.CharField(max_length=150, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approves for competition')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150, unique=True)),
                ('ctfd_team_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='registration.specialpassregistration')),
            ],
        ),
    ]
