# Generated by Django 6.0.1 on 2026-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpassregistration',
            name='firstname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='firstname1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='firstname2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='firstname3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='firstname4',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='firstname5',
            field=models.CharField(max_length=150),
        ),
    ]
