# Generated by Django 6.0.1 on 2026-02-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_basicpassregistration_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialpassregistration',
            name='discord_id4',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='discord_id5',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='email4',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='email5',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='firstname4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='firstname5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='lastname4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='lastname5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='school4',
            field=models.CharField(blank=True, choices=[('NSCS', 'National School of Cybersecurity'), ('ENSIA', 'National School of Artificial Intelligence'), ('NHSM', 'National Higher School of Mathematics'), ('NHSAST', 'National Higher School of Autonomous Systems Technology'), ('NHSNNT', 'National Higher School of Nano And Nanotechnology'), ('ESI', 'National School of Computer Science'), ('ESI-SBA', 'National School of Computer Science Sidi Bel Abbes'), ('ESTIN', 'Higher School in Computer Science and Digital Technologies'), ('NIT', 'Numidia Institute of Technology'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='school5',
            field=models.CharField(blank=True, choices=[('NSCS', 'National School of Cybersecurity'), ('ENSIA', 'National School of Artificial Intelligence'), ('NHSM', 'National Higher School of Mathematics'), ('NHSAST', 'National Higher School of Autonomous Systems Technology'), ('NHSNNT', 'National Higher School of Nano And Nanotechnology'), ('ESI', 'National School of Computer Science'), ('ESI-SBA', 'National School of Computer Science Sidi Bel Abbes'), ('ESTIN', 'Higher School in Computer Science and Digital Technologies'), ('NIT', 'Numidia Institute of Technology'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='skills4',
            field=models.TextField(blank=True, choices=[('Cryptography', 'Cryptography'), ('Web Security', 'Web Security'), ('PWN & Binary Exploitation', 'PWN & Binary Exploitation'), ('Reverse Engineering', 'Reverse Engineering'), ('Forensics', 'Forensics'), ('OSINT', 'OSINT'), ('Web Development', 'Web Development'), ('Programming', 'Programming'), ('problem Solving', 'Problem Solving'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='skills5',
            field=models.TextField(blank=True, choices=[('Cryptography', 'Cryptography'), ('Web Security', 'Web Security'), ('PWN & Binary Exploitation', 'PWN & Binary Exploitation'), ('Reverse Engineering', 'Reverse Engineering'), ('Forensics', 'Forensics'), ('OSINT', 'OSINT'), ('Web Development', 'Web Development'), ('Programming', 'Programming'), ('problem Solving', 'Problem Solving'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='student_id4',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='student_id5',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='year4',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year ')], null=True),
        ),
        migrations.AlterField(
            model_name='specialpassregistration',
            name='year5',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year ')], null=True),
        ),
    ]
