# Generated by Django 6.0.1 on 2026-02-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128)),
                ('base_points', models.IntegerField(choices=[(5, '5 points'), (10, '10 points'), (15, '15 points'), (20, '20 points'), (30, '30 points'), (50, '50 points')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['base_points'],
            },
        ),
        migrations.CreateModel(
            name='TokenSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_submissions', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tokens.token')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('team', 'token')},
            },
        ),
    ]
