# Generated by Django 6.0.1 on 2026-02-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='base_points',
            field=models.IntegerField(choices=[(5, '5 points'), (10, '10 points'), (15, '15 points'), (20, '20 points'), (30, '30 points'), (40, '40 points'), (50, '50 points'), (60, '60 points')]),
        ),
    ]
